### PR TITLE
add option to specify csp nonce on injected script

### PR DESCRIPTION
**Pull request by TheTrueRandom**
add option to specify csp nonce on injected script, see https://developers.google.com/tag-manager/web/csp

### CODE REVIEW

**Comment by MatteoGabriele** [comment]
close for inactivity

**Comment by TheTrueRandom** [comment]
why not consider merging?

**Comment by TheTrueRandom** [comment]
@MatteoGabriele

**Comment by MatteoGabriele** [comment]
test were failing and PR wasn't updated with master either for quite a lot of time, so I just closed it for inactivity.
if you take this up and running, we talk about merging it :)
nothing personal

**Pull request closed without merging**
