### PR TITLE
Build library using rollup

### PR DESCRIPTION
**Pull request by vladimyr**
This PR swaps `webpack` powered build system with full featured `rollup` powered one. 🚀

### CODE REVIEW

**Comment by MatteoGabriele** [comment]
I'm sorry but I'm not willing to switch to rollup right now and also you forgot that the linter and tests are based on webpack so they don't work right now and dependencies are broken

**Comment by MatteoGabriele** [comment]
I did open a ticket to look into multiple builds #43

**Comment by vladimyr** [comment]
> you forgot that the linter and tests are based on webpack so they don't work right now and dependencies are broken

Linter and tests are based on webpack? ESLint and jest are being used, how exactly do they depend on webpack?

Dependencies are broken? What does that mean? You only have dev dependencies and they could be broken but I certainly did lint, test and build before commiting and CI job succeeded indicating they are not?

I get that you aren't in the mood for change atm but the rest of your response is confusing 🤔

**Comment by MatteoGabriele** [comment]
@vladimyr the compression package, eslint and jest loader are dependent on webpack, without webpack when installing all the dependencies there are warnings of  unmet dependencies: webpack :) 

Screenshot 2019-12-30 at 15 38 01

**Comment by vladimyr** [comment]
Ok, that makes sense however what it really means is that I forgot to remove two obsolete dev dependencies: `compression-webpack-plugin` and `eslint-loader` that expect webpack as their peer dependency.

`eslint-plugin-jest` is transiently asking for typescript peer dependency and it has nothing to do with webpack.

Bottom line, nothing listed here is _dependent_ on webpack, just remove those two obsolete dependencies and your issue is gone.

**Comment by vladimyr** [comment]
> Bottom line, nothing listed here is _dependent_ on webpack, just remove those two obsolete dependencies and your issue is gone.

...finally did that and here is the result (don't forget to unfold `yarn` _section_): 
https://travis-ci.com/vladimyr/vue-gtag/builds/142714606#L207

Only thing that is left is this `eslint-plugin-jest` warning but guess what you have it also 😉
https://travis-ci.org/MatteoGabriele/vue-gtag/jobs/631103981#L206 

Let me know if you are interested in pursing this so I can create new pr...

**Pull request closed without merging**
