### PR TITLE
fix: no data reporting

### LINKED ISSUE #143: GoogleAnalytics not being added
### Description

I followed the documentation to add a new Analytics account to my vue application.
But events are not being sent to Analytics.

When I use the "Tag Assistant" plugin, it says that the gtag.js is set, but the analytics is not added.
I checked the devTools, and I couldn't find the analytics library being added.
```
<link href="https://www.googletagmanager.com" rel="preconnect">
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1234567-8" charset="utf-8"></script>
```

My setup is on the `main.js` file:
```
import VueGtag from 'vue-gtag';

Vue.use(
  VueGtag,
  {
    config: { id: 'UA-1234567-8' },
  },
  router
);
``` 

If I manually add this snippet to my `index.html`, it seems to work, but I thought that by using this plugin, this step should not be necessary.
```
window.dataLayer = window.dataLayer || [];
function gtag() {
  dataLayer.push(arguments);
}
gtag('js', new Date());

gtag('config', 'UA-1234567-8');
```

Am I missing something?
Any help would be appreciated!

Thanks in advance.

### Environment

vue-gtag@1.6.3
1. Operating system: Windows
2. Browser and version: Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)

### LINKED ISSUE #144: 1.6.3 seems to stop reporting data
### Description

Upgrading from 1.6.2 to 1.6.3 completely stopped the reporting of data.

### Expected behavior

Data should be reported as before.

### Actual behavior

The analytics dashboard reports 0 active people and 0 events in real time.

### Environment

Run this command in the project folder and fill in their results:

`npm ls vue-gtag`: 

Then, specify:

1. Operating system: MacOS 10.15.5
2. Browser and version: Chrome 83.0.4103.97

### PR DESCRIPTION
**Pull request by MatteoGabriele**
add config at start and config at pageview instead of page_view event

closes #144
closes #143

### CODE REVIEW

**Comment by codeofsumit** [comment]
great to see. Was just wondering why I haven't had data for the past two days

**Comment by MatteoGabriele** [comment]
@codeofsumit yeah sorry for that! I had lots of people complaining for an extra hit on load and I thought was that one but apparently, just like analytics, it needs an initial config event basically.

**Comment by leonexcc** [comment]
After this change i can't do this anymore:

```
Vue.use(VueGtag, {
    config: {
        id: CookieConsent.googleAnalyticsId,
        params: {
            send_page_view: false,
            anonymize_ip: true
        }
    },
    bootstrap: false
});
```

since now params will be ignored completely it will sent an initial page view and more importantly ignore the anonymize_ip settings.

i use this in a single page app and don't want to track the page view of the html file itself.

**Pull request merged**
